###############################################################
#  Generated by:      Cadence Innovus 22.11-s119_1
#  OS:                Linux x86_64(Host ID eda-2.EECS.Berkeley.EDU)
#  Generated on:      Fri Aug 16 18:38:00 2024
#  Design:            fir
#  Command:           write_db fir_FINAL -def -verilog
###############################################################
current_design fir
set_clock_gating_check -rise -setup 0 
set_clock_gating_check -fall -setup 0 
create_clock [get_ports {clk}]  -name clk -period 5.000000 -waveform {0.000000 2.500000}
set_propagated_clock  [get_ports {clk}]
set_load -pin_load -max  1  [get_ports {Out[15]}]
set_load -pin_load -min  1  [get_ports {Out[15]}]
set_load -pin_load -max  1  [get_ports {Out[14]}]
set_load -pin_load -min  1  [get_ports {Out[14]}]
set_load -pin_load -max  1  [get_ports {Out[13]}]
set_load -pin_load -min  1  [get_ports {Out[13]}]
set_load -pin_load -max  1  [get_ports {Out[12]}]
set_load -pin_load -min  1  [get_ports {Out[12]}]
set_load -pin_load -max  1  [get_ports {Out[11]}]
set_load -pin_load -min  1  [get_ports {Out[11]}]
set_load -pin_load -max  1  [get_ports {Out[10]}]
set_load -pin_load -min  1  [get_ports {Out[10]}]
set_load -pin_load -max  1  [get_ports {Out[9]}]
set_load -pin_load -min  1  [get_ports {Out[9]}]
set_load -pin_load -max  1  [get_ports {Out[8]}]
set_load -pin_load -min  1  [get_ports {Out[8]}]
set_load -pin_load -max  1  [get_ports {Out[7]}]
set_load -pin_load -min  1  [get_ports {Out[7]}]
set_load -pin_load -max  1  [get_ports {Out[6]}]
set_load -pin_load -min  1  [get_ports {Out[6]}]
set_load -pin_load -max  1  [get_ports {Out[5]}]
set_load -pin_load -min  1  [get_ports {Out[5]}]
set_load -pin_load -max  1  [get_ports {Out[4]}]
set_load -pin_load -min  1  [get_ports {Out[4]}]
set_load -pin_load -max  1  [get_ports {Out[3]}]
set_load -pin_load -min  1  [get_ports {Out[3]}]
set_load -pin_load -max  1  [get_ports {Out[2]}]
set_load -pin_load -min  1  [get_ports {Out[2]}]
set_load -pin_load -max  1  [get_ports {Out[1]}]
set_load -pin_load -min  1  [get_ports {Out[1]}]
set_load -pin_load -max  1  [get_ports {Out[0]}]
set_load -pin_load -min  1  [get_ports {Out[0]}]
set_clock_uncertainty 1 [get_clocks {clk}]
set_clock_groups -name __default_2 -asynchronous  -group  [get_clocks {clk}]
