#!/bin/bash

make sim/one_bit_comparator_structural_tb.vpd

make sim/one_bit_comparator_behavioral_tb.vpd

make sim/one_bit_comparator_always_tb.vpd

make sim/four_bit_comparator_always_tb.vpd

make sim/shift_register_structural_tb.vpd

make sim/shift_register_behavioral_tb.vpd

make sim/simple_counter_tb.vpd

make sim/decoder_4_to_16_tb.vpd


