
// Generated by Cadence Genus(TM) Synthesis Solution 22.11-s104_1
// Generated on: Aug 16 2024 18:09:47 PDT (Aug 17 2024 01:09:47 UTC)

// Verification Directory fv/fir 

module addertree_NUM_INPUT_BITS4_NUM_OUTPUT_BITS16(in0, in1, in2, in3,
     in4, Out);
  input [3:0] in0, in1, in2, in3, in4;
  output [15:0] Out;
  wire [3:0] in0, in1, in2, in3, in4;
  wire [15:0] Out;
  wire n_0, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  assign Out[8] = 1'b0;
  assign Out[9] = 1'b0;
  assign Out[10] = 1'b0;
  assign Out[11] = 1'b0;
  assign Out[12] = 1'b0;
  assign Out[13] = 1'b0;
  assign Out[14] = 1'b0;
  CLKINVX2 g768(.A (n_47), .Y (Out[15]));
  ADDFX1 g769__2398(.A (n_27), .B (n_13), .CI (n_45), .CO (n_47), .S
       (n_48));
  ADDFX1 g770__5107(.A (n_35), .B (n_28), .CI (n_43), .CO (n_45), .S
       (n_46));
  ADDFX1 g771__6260(.A (n_36), .B (n_33), .CI (n_41), .CO (n_43), .S
       (n_44));
  ADDFX1 g772__4319(.A (n_34), .B (n_25), .CI (n_39), .CO (n_41), .S
       (n_42));
  ADDFX1 g773__8428(.A (n_26), .B (n_23), .CI (n_37), .CO (n_39), .S
       (n_40));
  ADDFX1 g774__5526(.A (n_29), .B (in0[2]), .CI (n_24), .CO (n_37), .S
       (n_38));
  INVX2 g775(.A (n_32), .Y (n_36));
  INVX2 g776(.A (n_31), .Y (n_35));
  ADDFX1 g777__6783(.A (n_18), .B (in1[2]), .CI (n_17), .CO (n_33), .S
       (n_34));
  ADDFX1 g778__3680(.A (n_16), .B (in1[3]), .CI (n_21), .CO (n_31), .S
       (n_32));
  ADDFX1 g779__1617(.A (in4[1]), .B (in0[1]), .CI (n_14), .CO (n_29),
       .S (n_30));
  ADDHX1 g780__2802(.A (in2[2]), .B (n_22), .CO (n_27), .S (n_28));
  ADDFX1 g781__1705(.A (n_11), .B (in1[1]), .CI (n_19), .CO (n_25), .S
       (n_26));
  ADDFX1 g782__5122(.A (in4[2]), .B (in1[0]), .CI (in3[0]), .CO (n_23),
       .S (n_24));
  CLKINVX1 g783(.A (n_20), .Y (n_22));
  ADDHX1 g784__8246(.A (in3[3]), .B (n_10), .CO (n_20), .S (n_21));
  ADDHX1 g785__7098(.A (in3[1]), .B (n_12), .CO (n_18), .S (n_19));
  OR2X2 g786__6131(.A (n_15), .B (n_16), .Y (n_17));
  NOR2X1 g788__1881(.A (in2[0]), .B (in3[2]), .Y (n_16));
  AND2X2 g789__5115(.A (in3[2]), .B (in2[0]), .Y (n_15));
  AND2X2 g790__7482(.A (in4[0]), .B (in0[0]), .Y (n_14));
  INVX2 g791(.A (in2[3]), .Y (n_13));
  CLKINVX1 g792(.A (in4[3]), .Y (n_12));
  INVX2 g793(.A (in0[3]), .Y (n_11));
  CLKINVX1 g795(.A (in2[1]), .Y (n_10));
  BUFX16 drc_bufs(.A (n_38), .Y (Out[2]));
  BUFX16 drc_bufs796(.A (n_30), .Y (Out[1]));
  BUFX16 drc_bufs797(.A (n_48), .Y (Out[7]));
  BUFX16 drc_bufs798(.A (n_46), .Y (Out[6]));
  BUFX16 drc_bufs799(.A (n_40), .Y (Out[3]));
  BUFX16 drc_bufs800(.A (n_42), .Y (Out[4]));
  BUFX16 drc_bufs801(.A (n_44), .Y (Out[5]));
  BUFX16 drc_bufs802(.A (n_0), .Y (Out[0]));
  CLKXOR2X1 g2__4733(.A (in4[0]), .B (in0[0]), .Y (n_0));
endmodule

module REGISTER_R_N4(q, d, rst, clk);
  input [3:0] d;
  input rst, clk;
  output [3:0] q;
  wire [3:0] d;
  wire rst, clk;
  wire [3:0] q;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2, n_0, n_1,
       n_2, n_3;
  wire n_4, n_5, n_6, n_7;
  DFFX1 \q_reg[3] (.CK (clk), .D (n_7), .Q (q[3]), .QN (UNCONNECTED));
  DFFX1 \q_reg[2] (.CK (clk), .D (n_4), .Q (q[2]), .QN (UNCONNECTED0));
  DFFX1 \q_reg[0] (.CK (clk), .D (n_6), .Q (q[0]), .QN (UNCONNECTED1));
  DFFX1 \q_reg[1] (.CK (clk), .D (n_5), .Q (q[1]), .QN (UNCONNECTED2));
  NOR2X1 g7__6161(.A (rst), .B (n_0), .Y (n_7));
  NOR2X1 g8__9315(.A (rst), .B (n_3), .Y (n_6));
  NOR2X1 g9__9945(.A (rst), .B (n_1), .Y (n_5));
  NOR2X1 g10__2883(.A (rst), .B (n_2), .Y (n_4));
  CLKINVX2 g11(.A (d[0]), .Y (n_3));
  CLKINVX2 g12(.A (d[2]), .Y (n_2));
  CLKINVX2 g13(.A (d[1]), .Y (n_1));
  CLKINVX2 g14(.A (d[3]), .Y (n_0));
endmodule

module REGISTER_R_N4_22(q, d, rst, clk);
  input [3:0] d;
  input rst, clk;
  output [3:0] q;
  wire [3:0] d;
  wire rst, clk;
  wire [3:0] q;
  wire UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6, n_0,
       n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7;
  DFFX1 \q_reg[3] (.CK (clk), .D (n_7), .Q (q[3]), .QN (UNCONNECTED3));
  DFFX1 \q_reg[2] (.CK (clk), .D (n_4), .Q (q[2]), .QN (UNCONNECTED4));
  DFFX1 \q_reg[0] (.CK (clk), .D (n_6), .Q (q[0]), .QN (UNCONNECTED5));
  DFFX1 \q_reg[1] (.CK (clk), .D (n_5), .Q (q[1]), .QN (UNCONNECTED6));
  NOR2X1 g7__2346(.A (rst), .B (n_0), .Y (n_7));
  NOR2X1 g8__1666(.A (rst), .B (n_3), .Y (n_6));
  NOR2X1 g9__7410(.A (rst), .B (n_1), .Y (n_5));
  NOR2X1 g10__6417(.A (rst), .B (n_2), .Y (n_4));
  CLKINVX1 g11(.A (d[0]), .Y (n_3));
  CLKINVX1 g12(.A (d[2]), .Y (n_2));
  CLKINVX1 g13(.A (d[1]), .Y (n_1));
  CLKINVX1 g14(.A (d[3]), .Y (n_0));
endmodule

module REGISTER_R_N4_21(q, d, rst, clk);
  input [3:0] d;
  input rst, clk;
  output [3:0] q;
  wire [3:0] d;
  wire rst, clk;
  wire [3:0] q;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10, n_0,
       n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7;
  DFFX1 \q_reg[3] (.CK (clk), .D (n_7), .Q (q[3]), .QN (UNCONNECTED7));
  DFFX1 \q_reg[2] (.CK (clk), .D (n_4), .Q (q[2]), .QN (UNCONNECTED8));
  DFFX1 \q_reg[0] (.CK (clk), .D (n_6), .Q (q[0]), .QN (UNCONNECTED9));
  DFFX1 \q_reg[1] (.CK (clk), .D (n_5), .Q (q[1]), .QN (UNCONNECTED10));
  NOR2X1 g7__5477(.A (rst), .B (n_0), .Y (n_7));
  NOR2X1 g8__2398(.A (rst), .B (n_3), .Y (n_6));
  NOR2X1 g9__5107(.A (rst), .B (n_1), .Y (n_5));
  NOR2X1 g10__6260(.A (rst), .B (n_2), .Y (n_4));
  CLKINVX1 g11(.A (d[0]), .Y (n_3));
  CLKINVX1 g12(.A (d[2]), .Y (n_2));
  CLKINVX1 g13(.A (d[1]), .Y (n_1));
  CLKINVX1 g14(.A (d[3]), .Y (n_0));
endmodule

module REGISTER_R_N4_20(q, d, rst, clk);
  input [3:0] d;
  input rst, clk;
  output [3:0] q;
  wire [3:0] d;
  wire rst, clk;
  wire [3:0] q;
  wire UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14, n_0,
       n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7;
  DFFX1 \q_reg[3] (.CK (clk), .D (n_7), .Q (q[3]), .QN (UNCONNECTED11));
  DFFX1 \q_reg[2] (.CK (clk), .D (n_4), .Q (q[2]), .QN (UNCONNECTED12));
  DFFX1 \q_reg[0] (.CK (clk), .D (n_6), .Q (q[0]), .QN (UNCONNECTED13));
  DFFX1 \q_reg[1] (.CK (clk), .D (n_5), .Q (q[1]), .QN (UNCONNECTED14));
  NOR2X1 g7__4319(.A (rst), .B (n_0), .Y (n_7));
  NOR2X1 g8__8428(.A (rst), .B (n_3), .Y (n_6));
  NOR2X1 g9__5526(.A (rst), .B (n_1), .Y (n_5));
  NOR2X1 g10__6783(.A (rst), .B (n_2), .Y (n_4));
  CLKINVX1 g11(.A (d[0]), .Y (n_3));
  CLKINVX1 g12(.A (d[2]), .Y (n_2));
  CLKINVX1 g13(.A (d[1]), .Y (n_1));
  CLKINVX1 g14(.A (d[3]), .Y (n_0));
endmodule

module REGISTER_R_N4_19(q, d, rst, clk);
  input [3:0] d;
  input rst, clk;
  output [3:0] q;
  wire [3:0] d;
  wire rst, clk;
  wire [3:0] q;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18, n_0,
       n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7;
  DFFX1 \q_reg[3] (.CK (clk), .D (n_7), .Q (q[3]), .QN (UNCONNECTED15));
  DFFX1 \q_reg[2] (.CK (clk), .D (n_4), .Q (q[2]), .QN (UNCONNECTED16));
  DFFX1 \q_reg[0] (.CK (clk), .D (n_6), .Q (q[0]), .QN (UNCONNECTED17));
  DFFX1 \q_reg[1] (.CK (clk), .D (n_5), .Q (q[1]), .QN (UNCONNECTED18));
  NOR2X1 g7__3680(.A (rst), .B (n_0), .Y (n_7));
  NOR2X1 g8__1617(.A (rst), .B (n_3), .Y (n_6));
  NOR2X1 g9__2802(.A (rst), .B (n_1), .Y (n_5));
  NOR2X1 g10__1705(.A (rst), .B (n_2), .Y (n_4));
  CLKINVX1 g11(.A (d[0]), .Y (n_3));
  CLKINVX1 g12(.A (d[2]), .Y (n_2));
  CLKINVX1 g13(.A (d[1]), .Y (n_1));
  CLKINVX1 g14(.A (d[3]), .Y (n_0));
endmodule

module fir(clk, rst, In, Out);
  input clk, rst;
  input [3:0] In;
  output [15:0] Out;
  wire clk, rst;
  wire [3:0] In;
  wire [15:0] Out;
  wire [3:0] delay_chain0;
  wire [3:0] delay_chain1;
  wire [3:0] delay_chain2;
  wire [3:0] delay_chain3;
  wire [3:0] delay_chain4;
  wire UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22,
       UNCONNECTED23, UNCONNECTED24, UNCONNECTED25, n_6;
  wire n_9;
  addertree_NUM_INPUT_BITS4_NUM_OUTPUT_BITS16 add0(.in0 (delay_chain0),
       .in1 (delay_chain1), .in2 (delay_chain2), .in3 (delay_chain3),
       .in4 (delay_chain4), .Out ({n_9, UNCONNECTED25, UNCONNECTED24,
       UNCONNECTED23, UNCONNECTED22, UNCONNECTED21, UNCONNECTED20,
       UNCONNECTED19, Out[7:0]}));
  REGISTER_R_N4 delay_step0(.q (delay_chain0), .d (In), .rst (rst),
       .clk (clk));
  REGISTER_R_N4_22 delay_step1(.q (delay_chain1), .d (delay_chain0),
       .rst (rst), .clk (clk));
  REGISTER_R_N4_21 delay_step2(.q (delay_chain2), .d (delay_chain1),
       .rst (rst), .clk (clk));
  REGISTER_R_N4_20 delay_step3(.q (delay_chain3), .d (delay_chain2),
       .rst (rst), .clk (clk));
  REGISTER_R_N4_19 delay_step4(.q (delay_chain4), .d (delay_chain3),
       .rst (rst), .clk (clk));
  INVX16 g5(.A (n_6), .Y (Out[10]));
  INVX16 g7(.A (n_6), .Y (Out[11]));
  INVX16 g6(.A (n_6), .Y (Out[13]));
  INVX16 g3(.A (n_6), .Y (Out[14]));
  INVX16 g8(.A (n_6), .Y (Out[15]));
  INVX16 g2(.A (n_6), .Y (Out[8]));
  INVX16 g9(.A (n_6), .Y (Out[9]));
  INVX16 g4(.A (n_6), .Y (Out[12]));
  INVX8 g10(.A (n_9), .Y (n_6));
endmodule

